apiVersion: v1
kind: Service
metadata:
  name: flight-board
  labels:
    app: flight-board
spec:
  type: LoadBalancer
  selector:
    app: flight-board
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: flight-board-internal
  labels:
    app: flight-board
spec:
  type: ClusterIP
  selector:
    app: flight-board
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
